### ISSUE TITLE
Custom worker babel loader

### ISSUE THREAD

**Issue by mfbx9da4** [shadowwalker/next-pwa#137]
# Summary

Can't seem to use latest ecmascript syntax in a custom worker

# How To Reproduce

1. Create project with `worker/index.js`
2. Insert something like `let foo; console.log(foo?.a)`
3. next build

# Expected Behaviors

Should compile no errors

# Screenshots

```
> next build

Loaded env from /Users/david/code/.env
> [PWA] Compile client (static)
> [PWA] Auto register service worker with: /Users/david/code/node_modules/next-pwa/register.js
> [PWA] Service worker: /Users/david/code/public/sw.js
> [PWA]   url: /sw.js
> [PWA]   scope: /
> [PWA] Custom worker found: /Users/david/code/worker/index.js
> [PWA] Build custom worker: /Users/david/code/public/worker-3RAVrHIHaordzHiq0b3bN.js
> [PWA] Compile server
> [PWA] Failed to build custom worker
Hash: b3a560c6ecb87102409c
Version: webpack 4.44.1
Time: 247ms
Built at: 01/02/2021 1:20:56 PM
                          Asset      Size  Chunks  Chunk Names
worker-3RAVrHIHaordzHiq0b3bN.js  4.59 KiB       0  main
Entrypoint main = worker-3RAVrHIHaordzHiq0b3bN.js
[0] ./src/libs/webPush.js 546 bytes {0} [built] [failed] [1 error]
[1] ./worker/index.js 2.64 KiB {0} [built]
[2] ./node_modules/process/browser.js 5.29 KiB {0} [built]

ERROR in ./src/libs/webPush.js 39:47
Module parse failed: Unexpected token (39:47)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|     if (permission === 'granted') {
|       const subscription = await swRegistration.pushManager.getSubscription()
>       if (!isEndpointSentToServer(subscription?.endpoint)) {
|         const subscription = await createSubscription(swRegistration)
|         await registerSubscriptionOnServer(subscription)
 @ ./worker/index.js 2:0-84 66:31-49 66:50-76
info  - Creating an optimized production build .npm ERR! code ELIFECYCLE
```

# Additional Context

**Comment by shadowwalker** [comment]
Solved in version `5.0.3`

**Comment by harshzalavadiya** [comment]
@shadowwalker I'm still facing same issue in `v5.0.3`

```log
yarn run v1.22.10
$ next build
> [PWA] Compile client (static)
> [PWA] Auto register service worker with: /home/harsh/git/disk-file-next/node_modules/next-pwa/register.js
> [PWA] Service worker: /home/harsh/git/disk-file-next/.next/sw.js
> [PWA]   url: /sw.js
> [PWA]   scope: /
> [PWA] Custom worker found: /home/harsh/git/disk-file-next/worker/index.js
> [PWA] Build custom worker: /home/harsh/git/disk-file-next/.next/worker-xD0-ZTXQjJMv2tTysXd06.js
> [PWA] Compile server
> [PWA] Failed to build custom worker
Hash: ab417e8a5be1fd61d105
Version: webpack 4.44.1
Time: 119ms
Built at: 13/01/2021 5:50:57 pm
```

minimal example https://github.com/harshzalavadiya/next-pwa-custom-worker-error

**Comment by shadowwalker** [comment]
Reproduce
``` powershell
D:\Workspaces\tmp\next-pwa-custom-worker-error [master ≡]
λ  yarn build
yarn run v1.22.5
$ next build
> [PWA] Compile client (static)
> [PWA] Auto register service worker with: D:\Workspaces\tmp\next-pwa-custom-worker-error\node_modules\next-pwa\register.js
> [PWA] Service worker: D:\Workspaces\tmp\next-pwa-custom-worker-error\.next\sw.js
> [PWA]   url: /sw.js
> [PWA]   scope: /
> [PWA] Custom worker found: D:\Workspaces\tmp\next-pwa-custom-worker-error\worker\index.js
> [PWA] Build custom worker: D:\Workspaces\tmp\next-pwa-custom-worker-error\.next\worker-knJxsaKdbOuOxuamReOst.js
> [PWA] Compile server
> [PWA] Failed to build custom worker
Hash: beabba9ac4c2ec1deeeb
Version: webpack 4.44.1
Time: 123ms
Built at: 01/16/2021 11:34:48 AM

ERROR in Entry module not found: Error: Can't resolve 'babel-loader' in 'D:\Workspaces\tmp\next-pwa-custom-worker-error'
error Command failed with exit code 4294967295.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by shadowwalker** [comment]
@mfbx9da4 @harshzalavadiya Should be fixed in version `5.0.4`
