### ISSUE TITLE
start_url does not respond with a 200 when offline

### ISSUE THREAD

**Issue by zburk** [shadowwalker/next-pwa#75]
# Summary

When running Lighthouse on the [next-9 example](https://github.com/shadowwalker/next-pwa/tree/master/examples/next-9), Chrome reports that The start_url did respond, but not via a service worker. 

# How To Reproduce

1. Create project by clicking Gitpod on example
2. Run Lighthouse Progressive Web App on Mobile or Desktop

Link to minimal reproduce setup repository if any.

# Expected Behaviors
[Lighthouse.pdf](https://github.com/shadowwalker/next-pwa/blob/master/examples/next-9/lighthouse.pdf) on the example reports all PWA tests passing on Chrome using the example, but this is no longer the case as some PWA tests are not passing.

[Lighthouse Summary.pdf](https://github.com/shadowwalker/next-pwa/files/4858086/Lighthouse.Summary.pdf)

**Comment by comxd** [comment]
Same error for me, my "start_url" is equal to `/`, I have tried to set the `precacheHomePage: true` but no changes.

**Comment by shadowwalker** [comment]
Should be fixed with latest version

**Comment by zburk** [comment]
@shadowwalker I tried running the next-9 example again with v3.0.2 and still get the same error on Google Chrome's lighthouse.

**Comment by shadowwalker** [comment]
It works fine, you may need to clear cache and data under `application` tab in dev tools
![image](https://user-images.githubusercontent.com/9603375/86623957-55d11280-bf77-11ea-910b-5fe98be54ee2.png)

**Comment by zburk** [comment]
Yup can confirm it works! I had to clear the site data in the applications tab. Apparently incognito doesn't handle that
